# action.yml
name: 'maven settings'
description: 'create maven settings.xml file'
inputs:
  artifactory-url:
    description: 'artifactory url'
    required: true
    default: 'http://bla.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifactory-url }}
